# Cloudflare配置
name = "moonlight-blog"
main = "src/worker.js"
compatibility_date = "2024-04-12"

# Worker和Pages配置
[build]
command = "npm run build"
output_dir = "dist"
base_directory = "."

# KV命名空间配置
kv_namespaces = [
  { binding = "SESSIONS", id = "4628d0d463464eb695a5d42c7801700f" }
]

[site]
bucket = "dist"

# 开发环境配置
[dev]
port = 8788
local_protocol = "http"

# 环境变量
[vars]
NODE_ENV = "production"
NODE_VERSION = "16"
NPM_VERSION = "8"
ADMIN_USERNAME = "likem"
ADMIN_PASSWORD_HASH = "$2a$10$k0PWLodgQoyMuFL8NJLsfO0b7Wc4J.4/RFLTQG4v2pNGJUwdkbKTy"
JWT_SECRET = "63b65efd69399246549267e0959dffc9c5276cf1a5da2d28b4eba4dc54a56242"

# 路由配置
[[routes]]
pattern = "/*"
zone_name = "moonlight-blog.com" 