# Cloudflare配置
name = "moonlight-blog"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Pages配置
[pages]
build_output_dir = "dist"

# KV命名空间配置
kv_namespaces = [
  { binding = "SESSIONS", id = "4628d0d463464eb695a5d42c7801700f" }
]

[vars]
ADMIN_USERNAME = "likem"
ADMIN_PASSWORD_HASH = "$2a$10$k0PWLodgQoyMuFL8NJLsfO0b7Wc4J.4/RFLTQG4v2pNGJUwdkbKTy"
JWT_SECRET = "63b65efd69399246549267e0959dffc9c5276cf1a5da2d28b4eba4dc54a56242"

# 开发环境配置
[env.dev]
kv_namespaces = [
  { binding = "SESSIONS", id = "4628d0d463464eb695a5d42c7801700f" }
] 