backend:
  name: github
  repo: LKM-lkm/moonlight-blog
  branch: main
  base_url: https://decap-cms-github-oauth-api.lkm836972.workers.dev
  auth_endpoint: /api/auth
  app_id: Ov23liD7QdmvZRhsI1td

media_folder: "assets/images/articles" # 上传图片存放路径
public_folder: "/assets/images/articles"

collections:
  - name: "articles"
    label: "文章"
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "封面", name: "cover", widget: "image", required: false }
      - { label: "摘要", name: "excerpt", widget: "string", required: false }
      - { label: "正文", name: "body", widget: "markdown" } 